/**
 * @generated by scripts/architecture-sync.mjs — do not edit.
 *
 * Measured from the tree, so the map's numbers cannot drift from the code.
 * `UNCLAIMED` is what no module on the map covers: run the sync script, then
 * either give an existing module a wider pattern in coverage.json or add the
 * node the repo has been missing.
 */

export const MEASURED: Record<string, { count: number; loc: number }> = {
  'adapters': { count: 5, loc: 325 },
  'authguard': { count: 1, loc: 189 },
  'authsvc': { count: 2, loc: 282 },
  'boot': { count: 4, loc: 565 },
  'callback': { count: 1, loc: 21 },
  'client': { count: 1, loc: 488 },
  'diag': { count: 2, loc: 272 },
  'encode': { count: 3, loc: 309 },
  'fsm': { count: 1, loc: 379 },
  'mic': { count: 2, loc: 1221 },
  'picker': { count: 1, loc: 344 },
  'settings': { count: 1, loc: 655 },
  'spine': { count: 2, loc: 1039 },
  'store': { count: 1, loc: 100 },
  'styles': { count: 1, loc: 2312 },
  'surface': { count: 1, loc: 478 },
  'tokens': { count: 1, loc: 19 },
  'ui': { count: 2, loc: 1686 },
  'viz': { count: 1, loc: 231 },
}

export const UNCLAIMED: string[] = []
